# 코틀린에서 예외를 다루는 방법

1. try - catch - finally
2. Checked Exception & UnChecked Exception
3. try with resource

## try - catch - finally

Java ver

```java
public class Main {
	
	private int parseIntOrThrow(String str) {
		try {
			return Integer.parseInt(str)
		} catch (NumberFormatException e) {
			throw new IllegalArgumentException();
		} 
    }
}
```


kotlin ver

```kotlin

import java.lang.NumberFormatException
import java.util.IllegalFormatCodePointException

fun parseIntOrThrow(str: String): Int {
    try {
        return str.toInt()
    } catch (e: NumberFormatException) {
        throw IllegalArgumentException()
    }
}
```

try - catch 구문은 자바와 코틀린간 큰 차이가 없다.

## Checked Exception & UnChecked Exception

- 코틀린은 Checked Exception과 UnChecked Exception을 구분하지 않는다.
- 모두 UnChecked Exception 이다.
- 메서드 외부로 throws를 한다거나 할 필요가 없다.

## try with resources

```kotlin
fun readFile(path: String) {
    BufferedReader(FileReader(path)).use { reader ->
        print(reader.readLine())
    }
}
```

- kotlin에서는 try with resources 구문 자체가 사라지고 코틀린의 특성을 위해 만든 use라는 함수를 사용한다.


